# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LSHybridPageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'LSHybirdPage', :path => '../'

  # Pods for LSHybridPageDemo

  target 'LSHybridPageDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LSHybridPageDemoUITests' do
    # Pods for testing
  end

end
