# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JS_NativeBrige' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JS_NativeBrige
  pod 'SVProgressHUD', '~> 2.2.5'
  
  pod 'AFNetworking', '~> 2.6.3'
  
  target 'JS_NativeBrigeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JS_NativeBrigeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
